### PR TITLE
Fixes joystick normalization code

### LINKED ISSUE #89: Fix joystick movement 3d normalization bug
Joystick movement code is buggy atm. The normalization should be done on the 2d vector, not on the 3d diff.

### PR DESCRIPTION
**Pull request by orkaboy**
Fixes #89

### CODE REVIEW

File: src/seq/movement.rs [hunk 1]
```diff
@@ -72,13 +73,14 @@ impl SeqMove {
...
-        if climb {
+        let diff = *target - *player;
+        let mut diff2d = if climb {
             [diff.get_x(), diff.get_y()]
         } else {
             [diff.get_x(), diff.get_z()]
-        }
+        };
+        vec2::norm_mut(&mut diff2d);
+        diff2d
```
Comment (Eein) [inline src/seq/movement.rs:83]: I have no idea what any of this means

SHIP IT!

**Review by Eein — APPROVED** [review]

File: src/seq/movement.rs (hunk 1 above)
Comment (orkaboy) [reply src/seq/movement.rs:83]: Short of it is:

1. Calculate the 3d vector between the target point and the player's current position.
2. Create a 2d vector, discarding one of the axis (use y or z for the second depending on if we are climbing on a wall)
3. Normalize the result so the length of the 2d vector is 1 (which the joystick crate expects)
